### ISSUE TITLE
Automate publishing of new releases to hex.pm

### ISSUE THREAD

**Issue by SanGeeky** [kommitters/stellar_sdk#183] opened 2022-07-18 17:20 UTC
### Is your feature request related to a problem? Please describe.

Currently, the publishing process of new releases for this library to hex.pm is done manually. Automating this process adds value to the project and removes the need that a contributor to do this task.

### Describe the solution you'd like

Github actions provide different functionalities to publish the library using CI. Besides the latest documentation of HEX mentions the capability to do this easily, creating a `HEX_API_KEY` in the organization dashboard within [hex.pm](https://hex.pm/) and storing it in the repository secrets.

### Additional context

- [Publishing from CI](https://hex.pm/docs/publish#publishing-from-ci)
- [Secrets Github](https://docs.github.com/en/actions/security-guides/encrypted-secrets#creating-encrypted-secrets-for-a-repository)

**Comment by juanhurtado10** [comment] 2022-07-25 14:51
The issue is already solved. Changes will be released on v0.8.0

**Closed by juanhurtado10** 2022-07-25 14:51 UTC
Labels: 👍 Feature, ⛑ Needs triage
